parser:
  .ejs$: '@markuplint/ejs-parser'
parserOptions:
  ignoreFrontMatter: true
excludeFiles:
  - '.gitlab/**/*'
  - '.vscode/**/*'
  - '.git/**/*'
  - '.cache/**/*'
  - '.vlint/**/*'
  - '**/node_modules/**/*'
  - '**/coverage/**/*'
  - '**/dist/**/*'
  - '**/public/**/*'
rules:
  attr-duplication: true
  deprecated-attr: true
