extends:
  - stylelint-config-recommended
  - stylelint-config-recommended-scss
  - stylelint-prettier/recommended
plugins:
  - stylelint-scss
  - stylelint-prettier
customSyntax: postcss-scss
ignoreFiles:
  - .vscode/**
  - .git/**
  - .github/**
  - node_modules/**
  - dist/**
  - src/pages/**
  - src/scripts/**
rules:
  # stylelint-prettier
  prettier/prettier: true
